/// <reference types="node" />
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, extname } from "node:path";
import { pathToFileURL } from "node:url";
import type { WorkflowDefinition } from "./engine/types";
import type { WorkflowMeta } from "./types/workflow";
import { DEFAULT_WORKFLOW_META } from "./types/workflow";
import { importWorkflowYaml } from "./yaml/import";
import { importWorkflowJson } from "./json/import";
import { validateDefinition } from "./engine/validator";
import { exportWorkflowMermaid } from "./mermaid/export";
import { exportWorkflowDot } from "./graphviz/export";

interface LoadedWorkflow {
    definition: WorkflowDefinition;
    meta: WorkflowMeta;
}

async function loadFromModule(filePath: string): Promise<LoadedWorkflow> {
    const mod = (await import(pathToFileURL(filePath).href)) as Record<string, unknown>;

    // Try direct named exports first
    if (mod.definition) {
        return {
            definition: mod.definition as WorkflowDefinition,
            meta: (mod.meta as WorkflowMeta) ?? {
                ...DEFAULT_WORKFLOW_META,
                name: (mod.definition as WorkflowDefinition).name,
            },
        };
    }

    // Try default export
    if (mod.default && typeof mod.default === "object") {
        const def = mod.default as Record<string, unknown>;
        if (def.definition) {
            return {
                definition: def.definition as WorkflowDefinition,
                meta: (def.meta as WorkflowMeta) ?? {
                    ...DEFAULT_WORKFLOW_META,
                    name: (def.definition as WorkflowDefinition).name,
                },
            };
        }
    }

    // Try *Definition / *Meta pattern (generated by exportWorkflowTs)
    const defKey = Object.keys(mod).find((k) => k.endsWith("Definition"));
    if (defKey) {
        const metaKey = Object.keys(mod).find((k) => k.endsWith("Meta"));
        return {
            definition: mod[defKey] as WorkflowDefinition,
            meta: metaKey
                ? (mod[metaKey] as WorkflowMeta)
                : {
                      ...DEFAULT_WORKFLOW_META,
                      name: (mod[defKey] as WorkflowDefinition).name,
                  },
        };
    }

    throw new Error(
        `Could not find a workflow definition in "${filePath}". ` +
            "Export a 'definition' (and optional 'meta'), " +
            "or use the {name}Definition / {name}Meta pattern.",
    );
}

async function loadWorkflow(filePath: string): Promise<LoadedWorkflow> {
    const absPath = resolve(filePath);
    const ext = extname(absPath).toLowerCase();

    switch (ext) {
        case ".yaml":
        case ".yml": {
            const content = readFileSync(absPath, "utf8");
            return importWorkflowYaml(content);
        }
        case ".json": {
            const content = readFileSync(absPath, "utf8");
            return importWorkflowJson(content);
        }
        case ".js":
        case ".mjs":
        case ".ts":
        case ".mts":
            return loadFromModule(absPath);
        default:
            throw new Error(
                `Unsupported file format "${ext}". Use .yaml, .yml, .json, .js, or .ts`,
            );
    }
}

function printHelp(): void {
    const help = `Usage: symflow <command> <file> [options]

Commands:
  validate    Validate a workflow definition
  mermaid     Export workflow as Mermaid stateDiagram-v2
  dot         Export workflow as Graphviz DOT digraph

Options:
  -o, --output <file>   Write output to a file instead of stdout
  -h, --help            Show this help message

Supported file formats:
  .yaml, .yml           Symfony-compatible YAML config
  .json                 JSON with { definition, meta } shape
  .js, .ts              Module exporting definition and meta`;
    console.log(help);
}

async function main(): Promise<void> {
    const args = process.argv.slice(2);

    if (args.length === 0 || args.includes("-h") || args.includes("--help")) {
        printHelp();
        process.exit(0);
    }

    const command = args[0];
    const file = args[1];

    if (!file) {
        console.error("Error: Missing file argument.\n");
        printHelp();
        process.exit(1);
    }

    let outputFile: string | undefined;
    const outputIdx = args.indexOf("-o") !== -1 ? args.indexOf("-o") : args.indexOf("--output");
    if (outputIdx !== -1) {
        outputFile = args[outputIdx + 1];
        if (!outputFile) {
            console.error("Error: --output requires a file path.");
            process.exit(1);
        }
    }

    let loaded: LoadedWorkflow;
    try {
        loaded = await loadWorkflow(file);
    } catch (err) {
        console.error(
            `Error loading "${file}": ${err instanceof Error ? err.message : String(err)}`,
        );
        process.exit(1);
        return;
    }

    const { definition, meta } = loaded;

    switch (command) {
        case "validate": {
            const result = validateDefinition(definition);
            if (result.valid) {
                const msg =
                    `"${definition.name}" is valid` +
                    ` (${definition.places.length} places, ${definition.transitions.length} transitions)`;
                if (outputFile) {
                    writeFileSync(outputFile, msg + "\n");
                } else {
                    console.log(msg);
                }
            } else {
                const lines = [
                    `"${definition.name}" has ${result.errors.length} error(s):`,
                    "",
                    ...result.errors.map((e) => `  [${e.type}] ${e.message}`),
                ];
                const msg = lines.join("\n");
                if (outputFile) {
                    writeFileSync(outputFile, msg + "\n");
                }
                console.error(msg);
                process.exit(1);
            }
            break;
        }
        case "mermaid": {
            const output = exportWorkflowMermaid({ definition, meta });
            if (outputFile) {
                writeFileSync(outputFile, output);
                console.error(`Written to ${outputFile}`);
            } else {
                process.stdout.write(output);
            }
            break;
        }
        case "dot": {
            const output = exportWorkflowDot({ definition, meta });
            if (outputFile) {
                writeFileSync(outputFile, output);
                console.error(`Written to ${outputFile}`);
            } else {
                process.stdout.write(output);
            }
            break;
        }
        default:
            console.error(`Unknown command: "${command}"\n`);
            printHelp();
            process.exit(1);
    }
}

main().catch((err) => {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
});
