import type { WorkflowDefinition, Place, Transition } from "../engine";
import type { WorkflowMeta } from "../types";

interface ExportOptions {
    definition: WorkflowDefinition;
    meta: WorkflowMeta;
}

function escapePhpString(s: string): string {
    return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

function exportStringArray(arr: string[], _indent: string): string {
    if (arr.length === 0) return "[]";
    const items = arr.map((s) => `'${escapePhpString(s)}'`);
    return `[${items.join(", ")}]`;
}

function exportMetadataArray(obj: Record<string, string>, depth: number): string {
    const indent = "    ".repeat(depth);
    const innerIndent = "    ".repeat(depth - 1);
    const items = Object.entries(obj).map(
        ([key, value]) => `${indent}'${escapePhpString(key)}' => '${escapePhpString(value)}'`,
    );
    return `[\n${items.join(",\n")},\n${innerIndent}]`;
}

function exportPlace(place: Place): string {
    if (place.metadata && Object.keys(place.metadata).length > 0) {
        return `        new Place(name: '${escapePhpString(place.name)}', metadata: ${exportMetadataArray(place.metadata, 3)})`;
    }
    return `        new Place(name: '${escapePhpString(place.name)}')`;
}

function exportTransition(t: Transition): string {
    const parts: string[] = [];
    parts.push(`            name: '${escapePhpString(t.name)}'`);
    parts.push(`            froms: ${exportStringArray(t.froms, "            ")}`);
    parts.push(`            tos: ${exportStringArray(t.tos, "            ")}`);

    if (t.guard) {
        parts.push(`            guard: '${escapePhpString(t.guard)}'`);
    }
    if (t.consumeWeight !== undefined) {
        parts.push(`            consumeWeight: ${t.consumeWeight}`);
    }
    if (t.produceWeight !== undefined) {
        parts.push(`            produceWeight: ${t.produceWeight}`);
    }
    if (t.metadata && Object.keys(t.metadata).length > 0) {
        parts.push(`            metadata: ${exportMetadataArray(t.metadata, 3)}`);
    }

    return `        new Transition(\n${parts.join(",\n")},\n        )`;
}

/**
 * Generates a PHP config file that returns a Laraflow WorkflowDefinition
 * and WorkflowMeta. The output can be saved as a `.php` file and loaded
 * via `require` or `FileLoader::load()`.
 */
export function exportWorkflowPhp({ definition, meta }: ExportOptions): string {
    const placesStr = definition.places.map(exportPlace).join(",\n");
    const transitionsStr = definition.transitions.map(exportTransition).join(",\n");
    const initialMarkingStr = exportStringArray(definition.initialMarking, "        ");
    const typeClass = definition.type === "state_machine" ? "StateMachine" : "Workflow";
    const markingStoreClass = meta.marking_store === "property" ? "Property" : "Method";

    return `<?php

// Generated by symflow

use Laraflow\\Data\\Place;
use Laraflow\\Data\\Transition;
use Laraflow\\Data\\WorkflowDefinition;
use Laraflow\\Data\\WorkflowMeta;
use Laraflow\\Enums\\MarkingStoreType;
use Laraflow\\Enums\\WorkflowType;

return [
    'definition' => new WorkflowDefinition(
        name: '${escapePhpString(definition.name)}',
        type: WorkflowType::${typeClass},
        places: [
${placesStr},
        ],
        transitions: [
${transitionsStr},
        ],
        initialMarking: ${initialMarkingStr},
    ),
    'meta' => new WorkflowMeta(
        name: '${escapePhpString(meta.name)}',
        type: WorkflowType::${typeClass},
        markingStore: MarkingStoreType::${markingStoreClass},
        initialMarking: ${initialMarkingStr},
        supports: '${escapePhpString(meta.supports)}',
        property: '${escapePhpString(meta.property)}',
    ),
];
`;
}
